### ISSUE TITLE
Add kinds of flower

### ISSUE THREAD

**Issue by kome12** [ice-cream-the-fat-cat/my-niwa-backend#101]

**Comment by yukari-n-erb** [comment]
https://www.notion.so/flower-json-62a59d213c7f468e9592c6f727b5044e
<img width="724" alt="Screen Shot 2021-09-08 at 21 28 58" src="https://user-images.githubusercontent.com/45537257/132509497-404de5f9-5b4f-4156-8472-9edc93b8fa2e.png">
