### ISSUE TITLE
Rename garden's API endpoint to singular

### ISSUE THREAD

**Issue by yukari-n-erb** [ice-cream-the-fat-cat/my-niwa-backend#33]
Memo : 
Discuss garden's API name to change singular, and when we rename it.

## Path

before:
/API/v1/gardens/

after:
/API/v1/garden/

## Endpoint
before:
CreateGardens

after:
CreateGarden

**Comment by kome12** [comment]
@yukari-n-erb @daiHash Can we close this issue? Are we still going to update the endpoints?
