### ISSUE TITLE
Schema design for coins

### ISSUE THREAD

**Issue by kome12** [ice-cream-the-fat-cat/my-niwa-backend#57]
Schema design for coins

**Comment by kome12** [comment]
@yukari-n-erb @daiHash I don't think we'll have an explicit coins schema but I'm thinking we will store numCoins in a collection called UserAccounts

<img width="380" alt="スクリーンショット 2021-09-02 15 39 13" src="https://user-images.githubusercontent.com/770480/131794880-ce985129-7286-4c08-8f91-8c94772e76ac.png">

**Comment by yukari-n-erb** [comment]
I think the approach is reasonable.👍
If we do this schema, I guess we need to create the following endpoints for operate coin balance.

- AddCoinBalance(userid, coin)
- SubCoinBalance(userid, coin)

**Comment by yukari-n-erb** [comment]
memo:
- AddCoinBalance(userid, coin)
- SubCoinBalance(userid, coin)
- Add Flower from Gacha
