### ISSUE TITLE
Double check API documentation on Notion

### ISSUE THREAD

**Issue by kome12** [ice-cream-the-fat-cat/my-niwa-backend#98]
- what data is nullable for the response
- What data is required and what not for the request body

**Comment by daiHash** [comment]
@yukari-n-erb 
Is this done?

**Comment by yukari-n-erb** [comment]
Sorry, I'm late. I checked notion's page, and added GetGardenByGardenIdWithStartAndEndDate API.

https://www.notion.so/API-Documentation-1e1578e86b75488d8afa2f2ba467d918#0f7cc56af62f4239a9f2c9ecaf80f30a
